name: deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted

    env:
      username: nrjdalal
      reponame: ${{ github.event.repository.name }}

    defaults:
      run:
        working-directory: /srv

    steps:
      - run: sudo rm -rf $reponame
      - run: sudo git clone https://github.com/$username/$reponame.git
      - run: cd $reponame && sudo npm i
      - run: sudo rsync -r $reponame/ $reponame-prod
      - run: sudo cp proxyify.config.js $reponame-prod/config.js
